feat: Run piped frontend with unprivileged user
TeamPiped/Piped pull request #3806
Opened 2024-10-02 09:26 UTC by bjw-s

This PR allows running the Piped frontend container as an unprivileged user instead of running it with `root` permissions.

It also introduces two additional environment variables that allow some control over the number of nginx worker processes and the port nginx is exposed on.

2024-12-23 12:01 UTC, bjw-s commented
@Bnyro / @FireMasterK as you appear to be the last non-bots to have merged any PR's, is there anything I can / need to do to progress this PR?

2025-01-07 12:54 UTC, Bnyro requested changes
Please split the commit into two commits.

The changes to `docker/entrypoint.sh` are not related to running Piped as unprivilged user.

Apart from that, the changes generally look good to me and can be merged when split into different commits.

2025-01-14 17:29 UTC, bjw-s commented
> Please split the commit into two commits.
> 
> The changes to `docker/entrypoint.sh` are not related to running Piped as unprivilged user.
> 
> Apart from that, the changes generally look good to me and can be merged when split into different commits.

Thanks for the feedback! I've split up the PR in to two separate commits

2025-01-14 17:33 UTC, Bnyro approved these changes
Thank you!

2025-01-14 17:34 UTC, merged