[IN PROGRESS] UI2 changes
TeamPiped/Piped pull request #556
Opened 2021-10-22 19:56 UTC by IvRRimum

- [x] Replace favicons(without white background)
- [x] Video item design
- [x] No videos in my feed yet 
- [x] Change font to Montserrat
- [x] No subscriptions yet
- [x] Click on logo, take to root path
- [x] Move donations and github link to fixed location at the bottom right of the screen.
- [x] Make logout button work
- [x] If a person is not logged in dont show Feeds and subscriptions nav items
- [x] Add notifications( on subscription add) use this https://github.com/kyvg/vue3-notification ?
- [x] login button when not logged in, logout when logged in
- [x] Feeds - filters by the design
- [x] Subscriptions - Import/export by the design
- [x] Add search to pages(trending, feed, channel view, search view)
- [x] Fix autocomplete location
- [x] Search page filters by design
- [x] Fix infinite scroll in search, channel view, feeds pages
- [x] notification popup not seeable on mobile devices
- [x] Save the status of menu bar(collapse/expand) in browser memory
- [x] Video comments infinity scrool

2021-10-30 21:53 UTC, IvRRimum commented
@FireMasterK Are we good to merge?

2021-10-30 21:57 UTC, IvRRimum commented
Wait, no. Need to fix infinite scrool for comments

2021-10-30 23:08 UTC, IvRRimum commented
@FireMasterK Done

2021-10-31 18:00 UTC, FireMasterK requested changes

2021-10-31 18:00 UTC, FireMasterK commented on src/components/WatchVideo.vue
> +        <div v-show="!video.error" id="video-and-info">
Instead of using id, and document.getElement... You should use `ref="name"` and `this.$refs.name`

2022-01-15 01:33 UTC, VarLad commented
This needs to implement Chapters now as well I guess? 
@FireMasterK @IvRRimum

2022-09-05 19:58 UTC, Bnyro commented
See #1391 for Piped's future UI

2022-09-05 19:58 UTC, closed without merging